# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fr8z4PSYLuMe41SWMxMbzrwbfJhExrkS

#Assignment4
##control flow and conditional statements
"""



"""#Q1. Find the largest number from the given list, use for loop.
```
numbers = [12, 75, 150, 180, 145, 525, 50]
```
"""

numbers = [12, 75, 150, 180, 145, 525, 50]
largest_number=numbers[0]
for i in numbers:
  if i>largest_number:
    largest_number=i
print(f"largest number is:{largest_number}")

"""#Q2. Print all the even number between (1, 12)."""

n=int(input("enter number:"))
for i in range(1,n+1):
  if i%2==0:
    print(i)

"""#Q3. Calculate the sum of all numbers from 1 to a given number
    
    Expected Output:

    Enter number 10
    
    Sum is:  55
"""

list=[]
n=int(input("enter  number:"))
sum=0
for i in range(0,n+1):
  sum=sum+i
print("sum of all number is:",sum)

"""#Q4. Write a program to display only those numbers from a list that satisfy the following conditions

- The number must be divisible by five

- If the number is greater than 150, then skip it and move to the next number

- If the number is greater than 500, then stop the loop
"""

numbers = [12, 75, 150, 180, 145, 525, 50]
for i in numbers:
  if i>150:
    if i>500:
      break
    continue 
  if i%5==0:
    print(i)

"""#Q5. Print the given list in reverse order.

```
list1 = [10, 20, 30, 40, 50]
```
"""

list1 = [10, 20, 30, 40, 50]
list1[::-1]



